library(rpart)
library(rpart.plot)
library(pROC)
library(caret)
carRF <- read.csv("/Users/jiyewang/Desktop/Courses/Data_and_Text_Mining/A2/carRF.csv")
library(scorecard)
set.seed(7)
carRF_list <- split_df(carRF, ratio = 0.75)
cartrain <- carRF_list$train
cartest <- carRF_list$test

treecar1 = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 1))
treecar1
predcar1 = predict(treecar1, newdata = cartest, type = "class")
head(predcar1)
treecar1CM = table(cartest[["shouldBuy"]],predcar1)
treecar1CM
sum(diag(treecar1CM)/sum(treecar1CM))
rpart.plot(treecar1)
predcar1Pro = predict(treecar1, newdata = cartrain, type = "prob")
rocAcc1 = roc(cartrain$shouldBuy,predcar1Pro[,1])
rocGood1 = roc(cartrain$shouldBuy,predcar1Pro[,2])
rocUnacc1 = roc(cartrain$shouldBuy,predcar1Pro[,3])
rocVgood1 = roc(cartrain$shouldBuy,predcar1Pro[,4])
plot(rocUnacc1, col = "red")
par(new=TRUE)
plot(rocAcc1, col = "green")
par(new=TRUE)
plot(rocGood1, col = "blue")
par(new=TRUE)
plot(rocVgood1, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnacc1)),paste("Acc",auc(rocAcc1)),paste("Good",auc(rocGood1)),paste("Vgood",auc(rocVgood1))), col = c("red","green","blue","grey"), bty = "n")

treecar10 = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 10))
treecar10
predcar10 = predict(treecar10, newdata = cartest, type = "class")
head(predcar10)
treecar10CM = table(cartest[["shouldBuy"]],predcar10)
treecar10CM
sum(diag(treecar10CM)/sum(treecar10CM))
rpart.plot(treecar10)
predcar10Pro = predict(treecar10, newdata = cartrain, type = "prob")
rocAcc10 = roc(cartrain$shouldBuy,predcar10Pro[,1])
rocGood10 = roc(cartrain$shouldBuy,predcar10Pro[,2])
rocUnacc10 = roc(cartrain$shouldBuy,predcar10Pro[,3])
rocVgood10 = roc(cartrain$shouldBuy,predcar10Pro[,4])
auc(rocUnacc10)
plot(rocUnacc10, col = "red")
par(new=TRUE)
plot(rocAcc10, col = "green")
par(new=TRUE)
plot(rocGood10, col = "blue")
par(new=TRUE)
plot(rocVgood10, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnacc10)),paste("Acc",auc(rocAcc10)),paste("Good",auc(rocGood10)),paste("Vgood",auc(rocVgood10))), col = c("red","green","blue","grey"), bty = "n")

treecar50 = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 50))
treecar50
predcar50 = predict(treecar50, newdata = cartest, type = "class")
head(predcar10)
treecar50CM = table(cartest[["shouldBuy"]],predcar50)
treecar50CM
sum(diag(treecar50CM)/sum(treecar50CM))
rpart.plot(treecar50)
predcar50Pro = predict(treecar50, newdata = cartrain, type = "prob")
rocUnacc50 = roc(cartrain$shouldBuy,predcar50Pro[,3])
rocAcc50 = roc(cartrain$shouldBuy,predcar50Pro[,1])
rocGood50 = roc(cartrain$shouldBuy,predcar50Pro[,2])
rocVgood50 = roc(cartrain$shouldBuy,predcar50Pro[,4])
plot(rocUnacc50, col = "red")
par(new=TRUE)
plot(rocAcc50, col = "green")
par(new=TRUE)
plot(rocGood50, col = "blue")
par(new=TRUE)
plot(rocVgood50, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnacc50)),paste("Acc",auc(rocAcc50)),paste("Good",auc(rocGood50)),paste("Vgood",auc(rocVgood50))), col = c("red","green","blue","grey"), bty = "n")

treecar100 = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 100))
treecar100
predcar100 = predict(treecar100, newdata = cartest, type = "class")
head(predcar100)
treecar100CM = table(cartest[["shouldBuy"]],predcar100)
treecar100CM
sum(diag(treecar100CM)/sum(treecar100CM))
rpart.plot(treecar100)
predcar100Pro = predict(treecar100, newdata = cartrain, type = "prob")
rocUnacc100 = roc(cartrain$shouldBuy,predcar100Pro[,3])
rocAcc100 = roc(cartrain$shouldBuy,predcar100Pro[,1])
rocGood100 = roc(cartrain$shouldBuy,predcar100Pro[,2])
rocVgood100 = roc(cartrain$shouldBuy,predcar100Pro[,4])
plot(rocUnacc100, col = "red")
par(new=TRUE)
plot(rocAcc100, col = "green")
par(new=TRUE)
plot(rocGood100, col = "blue")
par(new=TRUE)
plot(rocVgood100, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnacc100)),paste("Acc",auc(rocAcc100)),paste("Good",auc(rocGood100)),paste("Vgood",auc(rocVgood100))), col = c("red","green","blue","grey"), bty = "n")

treecar130 = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 130))
treecar130
predcar130 = predict(treecar130, newdata = cartest, type = "class")
head(predcar130)
treecar130CM = table(cartest[["shouldBuy"]],predcar130)
treecar130CM
sum(diag(treecar130CM)/sum(treecar130CM))
rpart.plot(treecar130)
predcar130Pro = predict(treecar130, newdata = cartrain, type = "prob")
rocUnacc130 = roc(cartrain$shouldBuy,predcar130Pro[,3])
rocAcc130 = roc(cartrain$shouldBuy,predcar130Pro[,1])
rocGood130 = roc(cartrain$shouldBuy,predcar130Pro[,2])
rocVgood130 = roc(cartrain$shouldBuy,predcar130Pro[,4])
plot(rocUnacc130, col = "red")
par(new=TRUE)
plot(rocAcc130, col = "green")
par(new=TRUE)
plot(rocGood130, col = "blue")
par(new=TRUE)
plot(rocVgood130, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnacc130)),paste("Acc",auc(rocAcc130)),paste("Good",auc(rocGood130)),paste("Vgood",auc(rocVgood130))), col = c("red","green","blue","grey"), bty = "n")

cartrain = cartrain[,c(1:5,7)]
cartest = cartest[,c(1:5,7)]

treecarT = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = 75))
treecarT
predcarT = predict(treecarT, newdata = cartest, type = "class")
head(predcarT)
treecarTCM = table(cartest[["shouldBuy"]],predcarT)
treecarTCM
sum(diag(treecarTCM)/sum(treecarTCM))
rpart.plot(treecarT)
predcarTPro = predict(treecarT, newdata = cartrain, type = "prob")
predcarTPro
rocUnaccT = roc(cartrain$shouldBuy,predcarTPro[,3])
rocAccT = roc(cartrain$shouldBuy,predcarTPro[,1])
rocGoodT = roc(cartrain$shouldBuy,predcarTPro[,2])
rocVgoodT = roc(cartrain$shouldBuy,predcarTPro[,4])
plot(rocUnaccT, col = "red")
par(new=TRUE)
plot(rocAccT, col = "green")
par(new=TRUE)
plot(rocGoodT, col = "blue")
par(new=TRUE)
plot(rocVgoodT, col = "grey")
legend("bottomright",pch = c(15,15), legend = c(paste("Unacc",auc(rocUnaccT)),paste("Acc",auc(rocAccT)),paste("Good",auc(rocGoodT)),paste("Vgood",auc(rocVgoodT))), col = c("red","green","blue","grey"), bty = "n")

test_accuracy <- function(ilists){
  a <- list()
  for(ilist in ilists){
    treecarF = rpart(shouldBuy~., data = cartrain, method = "class", control = rpart.control(minsplit = ilist))
    predcarF = predict(treecarF, newdata = cartest, type = "class")
    treecarFCM = table(cartest[["shouldBuy"]],predcarF)
    b = list(sum(diag(treecarFCM)/sum(treecarFCM)))
    a=c(a,b)
  }
  return(a)
}

minsplits = c(1:130)
test_function <- test_accuracy(minsplits)
test_function
plot(minsplits,test_accuracy(minsplits))

car5control = trainControl(method = "repeatedcv", number = 5, repeats = 3)
randomForest_car5 = train(cartrain[,1:6], cartrain[["shouldBuy"]], method = "rf", metric = "Accuracy", trControl = car5control)
print(randomForest_car5)
varImp(randomForest_car5)
ggplot(varImp(randomForest_car5))

car7control = trainControl(method = "repeatedcv", number = 7, repeats = 3)
randomForest_car7 = train(cartrain[,1:6], cartrain[["shouldBuy"]], method = "rf", metric = "Accuracy", trControl = car7control)
print(randomForest_car7)
varImp(randomForest_car7)
ggplot(varImp(randomForest_car7))

car10control = trainControl(method = "repeatedcv", number = 10, repeats = 3)
randomForest_car10 = train(cartrain[,1:6], cartrain[["shouldBuy"]], method = "rf", metric = "Accuracy", trControl = car10control)
print(randomForest_car10)
varImp(randomForest_car10)
ggplot(varImp(randomForest_car10))

car15control = trainControl(method = "repeatedcv", number = 15, repeats = 3)
randomForest_car15 = train(cartrain[,1:6], cartrain[["shouldBuy"]], method = "rf", metric = "Accuracy", trControl = car15control)
print(randomForest_car15)
varImp(randomForest_car15)
ggplot(varImp(randomForest_car15))

carTcontrol = trainControl(method = "repeatedcv", number = 10, repeats = 11)
randomForest_carT = train(cartrain[,1:6], cartrain[["shouldBuy"]], method = "rf", metric = "Accuracy", trControl = carTcontrol)
print(randomForest_carT)
varImp(randomForest_carT)
ggplot(varImp(randomForest_carT))

